[tool.poetry]
name = "presentation"
version = "0.1.0"
description = ""
authors = ["Nao Pross <np@0hm.ch>"]

[tool.poetry.dependencies]
python = "^3.7"
manim = "^0.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
